version: "3"

networks:
  internalnet:
    ipam:
      driver: default
      config:
        - subnet: 172.168.1.0/16
services:
  ntity-01:
    image: ntity/node:latest
    restart: always
    container_name: ntity-01
    hostname: ntity-01
    volumes:
      - /data/blockchain/ntity-01:/blockchain
      - /data/blockchain/password:/blockchain/password
      - ./files/config.toml:/blockchain/config.toml
      - /data/blockchain/ntity.genesis.json:/blockchain/ntity.genesis.json
      - ./files/app.json:/root/eth-net-intelligence-api/app.json
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    networks:
      internalnet:
        ipv4_address: 172.168.1.2
    environment:
      - NETWORK_ID=197710212030
      - WALLET=0x57616c6c6574
      - GETH_OPTS=--nodiscover --allow-insecure-unlock --password /blockchain/password/password.txt --mine --config /blockchain/config.tom
      - DATA_DIR=/blockchain
      - FREEZER_DIR=/blockchain/freezer
volumes:
  blockchain:
