FROM arm64v8/golang:1.18.3-bullseye as builder

WORKDIR /

RUN git clone https://github.com/ethereum/go-ethereum.git && cd ./go-ethereum && git checkout tags/v1.10.20 && make geth

FROM arm64v8/alpine:3.15

RUN apk add --no-cache ca-certificates bash nodejs npm perl git
COPY --from=builder /go-ethereum/build/bin/geth /usr/local/bin/

RUN cd /root &&\
    git clone https://github.com/ethereum/eth-net-intelligence-api &&\
    cd eth-net-intelligence-api &&\
    npm install &&\
    npm install -g pm2

# Shell script
COPY ./run.sh /root/run.sh
RUN chmod +x /root/*.sh

# Misc
EXPOSE 8545 8546 30303 30303/udp
CMD ["/root/run.sh"]
