# Image definition
FROM arm64v8/golang:1.15-alpine3.12 as builder

RUN apk add make gcc musl-dev linux-headers git

WORKDIR /

RUN git clone https://github.com/ethereum/go-ethereum.git && cd ./go-ethereum && git checkout tags/v1.10.8 && make geth

FROM arm64v8/alpine:latest

RUN apk add --no-cache ca-certificates bash nodejs nodejs-npm perl git
COPY --from=builder /go-ethereum/build/bin/geth /usr/local/bin/

RUN cd /root &&\
    git clone https://github.com/ethereum/eth-net-intelligence-api &&\
    cd eth-net-intelligence-api &&\
    npm install &&\
    npm install -g pm2

# Shell script
COPY ./Dockerfile/run.sh /root/run.sh
RUN chmod +x /root/*.sh

# Misc
EXPOSE 8545 8546 30303 30303/udp
CMD ["/root/run.sh"]

